# Generated by Django 2.2.1 on 2019-12-17 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('referrals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.PositiveIntegerField(max_length=12)),
                ('refer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refer', to='referrals.Refer')),
            ],
        ),
    ]
