# Generated by Django 2.2.1 on 2019-12-17 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reward',
            name='points',
            field=models.PositiveIntegerField(),
        ),
    ]
